spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bachelor
    username: test
    password: Test1234

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

server:
  port: 8002